### ISSUE TITLE
Create a mini database to collect user input

### ISSUE THREAD

**Issue by medic-code** [eamon0989/LaunchSchoolTimeEstimator#36]
Only had a very quick look at the code, so sorry if this is already implemented in a much simpler way,

But the idea would be to create a form that actually ask users who have completed a course to input  how many hours it took them to finish a particular course. That way you could compare against other students and have a better idea of a student averages per course rather than based upon the user's own experience only.

Basic architecture would go something like this:

Basic Form --> Express (The node framework) -> Database (MongoDB)  (Hosting by MongoDb Atlas)--> Fields for each course and storing hours to completion -> Compute an average -> Display contents via the DOM manipulation.

I've had some experience with express and MongoDb so could probably do the backend part of it. Forms I have some experience in React but would probably want to do a pure JS form given its pure JS code currently.

Let me know what you think, happy to contribute to this if it makes any sense. I realise it's an ambitious goal, particularly for those who are just in JS120 and below!

**Comment by eamon0989** [comment]
That would be great. To be honest the only reason I didn't impliment that is that I haven't studied databases yet, I had thought of adding it as a feature in the future. Feel free to impliment the backend part if you like, we would be delighted to have it!

**Comment by medic-code** [comment]
Yep might as well assign this one to me then! Happy to pair program this with someone if someone wants to learn abit about node,express, mongodb. Again I appreciate that it's scope creep for those who are full time LS students and wouldn't want to impose on that!

**Comment by eamon0989** [comment]
Awesome thanks very much!
