### ISSUE TITLE
Input stays in the input text area after clicking submit

### ISSUE THREAD

**Issue by eamon0989** [eamon0989/LaunchSchoolTimeEstimator#4]
After clicking submit, text area should be cleared

**Comment by medic-code** [comment]
Not quite sure what is meant here. When you click submit it goes to the estimated time to finish screen. When clicking the reset button the input text area is cleared.

**Comment by eamon0989** [comment]
You're right, this is no longer relevant. I wrote it for v1.0 of the app.
